import { defineConfig } from 'cspell';

export default defineConfig({
  version: '0.2',
  ignoreWords: [
    'prebuild',
    'ngsw',
    'fontsource',
    'noopener',
    'noreferrer',
    'Subchunk',
    'apphosting',
    'headerless',
    'remoteconfig',
    'Kore',
    'Sadachbia',
    'Sulafat',
    'Achird',
    'Laomedeia',
    'Erinome',
    'Autonoe',
    'Aoede',
    'Orus',
    'Sadaltager',
    'APPCHECK',
    'grantaccess',
    'Gapless',
    'prerendering',
    'Sandboxing',
    'recaptcha',
    'sandboxed',
    'multimodal',
    'developerknowledge',
    'autonumber',
    'Wayfinding',
    'wayfinder',
    'gaplessly',
  ],
  ignorePaths: [
    'node_modules',
    'dist',
    'coverage',
    '.git',
    '.vscode',
    '.idea',
    '*.spec.ts',
    'firebase.config.json',
    'ngsw-config.json',
    'firebase.config',
    'skills-lock.json',
  ],
});
